[package]
name = "src_ttl_extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "1.0.0"
csv = "1.1.6"

[dependencies.pnet]
version = "0.31.0"
features = ["std", "pcap", "pnet_datalink"]